---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/stores":
    post:
      summary: Creates a store
      tags:
      - Stores
      parameters: []
      responses:
        '201':
          description: store created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/v1/stores/{id}":
    get:
      summary: Retrieves a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: store found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - id
                - name
        '404':
          description: store not found
    put:
      summary: Updates a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: store updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - id
                - name
        '404':
          description: store not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Remove a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: store removed
        '404':
          description: store not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
