default: &default
  adapter: postgresql
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sopha-api-test_development
test:
  <<: *default
  database: sopha-api-test_test
production:
  <<: *default
  database: sat-prod
  username: satuser
  password: <%= ENV['SOPHA_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['SOPHA_API_DATABASE_HOST'] %>
  port: <%= ENV['SOPHA_API_DATABASE_PORT'] %>
